# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mytheme"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

[ -f ${HOME}/.aliases ] && source ${HOME}/.aliases

plugins=(git python osx brew history-substring-search virtualenvwrapper vi-mode)

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

bindkey '^R' history-incremental-search-backward


if [ `uname` = "Darwin" ]; then
    nbtunnel () {
        ssh -q -N -f -L localhost:6500:localhost:7000 $1 \
            && open -a safari https://localhost:6500
    }
    nbstart () {
        if [[ $# == 1 ]]; then
            workon $1 && jupyter notebook
        elif [[ $# == 0 ]]; then
            jupyter notebook
        else;
            echo "Usage: $0 [venv]"
        fi
    }
elif [ `expr substr $(uname -s) 1 5` = "Linux" ]; then
    if [ -z "$TMUX" ]; then
        function refresh { }
        if [[ -n "$SSH_AUTH_SOCK" && \
            "`readlink ~/.ssh/ssh_auth_sock`" != "$SSH_AUTH_SOCK" ]]; then
            ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
        fi
        tmux attach || tmux new -A
    else
        function refresh {
            export $(tmux show-environment | grep "^SSH_AUTH_SOCK")
        }
    fi

    function preexec {
        refresh
    }

    nbstart () {
        workon $1 && \
            jupyter notebook \
            --certfile=~/projects/dots/all/security/mycert.pem \
            --no-browser --port=7000
    }
else

fi
