# Source zprofile for non-login shells (login shells already source it)
[[ ! -o login ]] && source "${HOME}/.zprofile"

export EDITOR='nvim';

export DOTS_HOME=${WORKSPACE}/dots;

# Regular Colors
export COLOR_OFF=$'\e[0m'             # Text Reset
export COLOR_BLACK=$'\e[0;30m'        # Black
export COLOR_RED=$'\e[0;31m'          # Red
export COLOR_GREEN=$'\e[0;32m'        # Green
export COLOR_YELLOW=$'\e[0;33m'       # Yellow
export COLOR_BLUE=$'\e[0;34m'         # Blue
export COLOR_PURPLE=$'\e[0;35m'       # Purple
export COLOR_CYAN=$'\e[0;36m'         # Cyan
export COLOR_WHITE=$'\e[0;37m'        # White

alias editor="nvim"
alias vim='nvim'
alias zshconfig="nvim ~/.zshrc"
alias vimlarge="nvim -u NONE -U NONE -N"
alias vimconfig="nvim ~/.config/nvim/init.lua"
alias vimplugins="nvim ~/.config/nvim/lua/plugins/core.lua"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias cx="chmod +x "
alias rm="rm -i"
alias mv="mv -i"
alias wgetn="wget --no-check-certificate";
alias ipython='ipython --TerminalInteractiveShell.editing_mode=vi'
alias tensorboard="CUDA_VISIBLE_DEVICES= tensorboard";



reset-ssh() {
    sudo netstat -apn | grep -w 2224 | awk '{ print $7 }' | sed 's/\(.*\)\/.*/\1/' | sort -u | xargs -I{} kill -9 {};
}

_ssh_agent_maybe_launch() {
  if [[ -z "$SSH_AGENT_PID" ]]; then
    if command -v keychain > /dev/null 2>&1; then
      eval $(keychain --eval --quiet --inherit any)
    else
      eval $(ssh-agent -s) > /dev/null 2>&1
    fi
  fi
  _ssh_agent_attach_fixed_path
}

_ssh_agent_attach_fixed_path() {
  # Maintain symlink to socket (like Linux section does)
  if [[ -n "$SSH_AUTH_SOCK" && "$SSH_AUTH_SOCK" =~ ^/tmp/ ]]; then
    # Create symlink if it doesn't exist or points to wrong location
    if [[ ! -L ~/.ssh/ssh_auth_sock ]] || \
       [[ "$(readlink -f ~/.ssh/ssh_auth_sock)" != "$(readlink -f "$SSH_AUTH_SOCK")" ]]; then
	ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
    fi
  fi
}

# =====================================================================================================================
# ================================================= OhMyZsh Settings ==================================================
# =====================================================================================================================

export ZSH=${HOMEDIR}/.oh-my-zsh

if [[ ! -f ${ZSH}/oh-my-zsh.sh ]]; then
    # Remove broken/partial oh-my-zsh directory if it exists
    if [[ -d ${ZSH} && "${ZSH}" == */.oh-my-zsh && "${ZSH}" == ${HOME}/* ]]; then
        rm -rf ${ZSH}
    fi

    RUNZSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

    [[ ! -d ${ZSH}/custom/plugins/fzf ]] && git clone https://github.com/junegunn/fzf.git ${ZSH}/custom/plugins/fzf;
    ${ZSH}/custom/plugins/fzf/install --bin;
    [[ ! -d ${ZSH}/custom/plugins/fzf-zsh ]] && git clone https://github.com/Treri/fzf-zsh.git ${ZSH}/custom/plugins/fzf-zsh;
    [[ ! -d ${ZSH}/custom/plugins/zsh-uv-env ]] && git clone https://github.com/matthiasha/zsh-uv-env.git ${ZSH}/custom/plugins/zsh-uv-env;
    _update_env;

    _safe_symlink "${DOTS_HOME}/all/zsh/bashrc" "${HOMEDIR}/.bashrc"
    _safe_symlink "${DOTS_HOME}/all/zsh/zprofile" "${HOMEDIR}/.zprofile"
    _safe_symlink "${DOTS_HOME}/all/zsh/zshrc" "${HOMEDIR}/.zshrc"
    _safe_symlink "${DOTS_HOME}/all/zsh/mytheme.zsh-theme" "${ZSH}/custom/themes/mytheme.zsh-theme"
fi
export FZF_BASE=${ZSH}/custom/plugins/fzf;
# export FZF_DEFAULT_COMMAND="fd --type file"

if [[ -f "${ZSH}/custom/themes/mytheme.zsh-theme" ]]; then
    ZSH_THEME="mytheme";
else
    ZSH_THEME="maran";
fi

export HISTFILE=${HOMEDIR}/.zsh_history;
export HISTFILESIZE=5000;
export HISTSIZE=1000;

DISABLE_AUTO_UPDATE=true
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(git tmux python brew history-substring-search uv vi-mode fzf-zsh zsh-uv-env)

# do not forget to make zsh directories properly owned in case of compinit problmes
# chown -R $USER $ZSH_INSTALL_PREFIX/share/zsh/
# chmod -R 755 $ZSH_INSTALL_PREFIX/share/zsh/

source ${ZSH}/oh-my-zsh.sh

if command -v zoxide &>/dev/null; then
    eval "$(zoxide init zsh)"
fi

_fcd_or_complete() {
    if [[ -z "$BUFFER" ]]; then
        local dir
        dir=$({
            if command -v zoxide &>/dev/null; then
                zoxide query -l 2>/dev/null | head -20
            fi
            find . -maxdepth 2 -type d 2>/dev/null | sed 's|^\./||'
        } | awk '!seen[$0]++' | fzf --height=40% --reverse)
        if [[ -n "$dir" ]]; then
            BUFFER="cd $dir"
            zle accept-line
        fi
    else
        zle expand-or-complete
    fi
}
zle -N _fcd_or_complete
bindkey '^I' _fcd_or_complete

# TODO FIXME
# eval "$(/home/vsvetlov/miniconda3/bin/conda shell.zsh hook)"

# Reset pane title when returning to prompt (after subprocess exits)
if [[ -n "$TMUX" ]]; then
    _reset_pane_title() { printf '\033]2;%s\033\\' "${PWD/#$HOME/~}" }
    precmd_functions+=(_reset_pane_title)
fi

if [[ -f "${HOMEDIR}/.secrets.rc" ]]; then
    source "${HOMEDIR}/.secrets.rc"
fi

# =====================================================================================================================
# =============================================== OS Specific Settings ================================================
# =====================================================================================================================
if [[ $IS_DARWIN == true || $IS_WSL == true ]]; then
    if [[ $IS_WSL == true ]]; then
        export BROWSER=wslview
    fi
    _ssh_agent_maybe_launch;
    if [[ -z "$WEZTERM_NO_TMUX" && "${#TMUX}" -eq 0 ]]; then
        tmux attach || tmux new -A
    fi
elif [[ $IS_LINUX == true ]]; then
    if [[ -L "${HOME}/.zshrc" ]]; then
        if [[ "${#TMUX}" -eq 0 ]]; then
	        _ssh_agent_attach_fixed_path;
            tmux attach || tmux new -A
        fi
    fi
else
    echo "${COLOR_RED}Unknown host $(uname -s)${COLOR_OFF}";
fi

