personality = "pragmatic"
model = "gpt-5.4"
model_reasoning_effort = "high"
# should be placed in ~/.codex/config.toml

[features]
web_search_request = true        # allow the model to request web searches

[sandbox_workspace_write]
network_access = true

[projects.'/home/vsvetlov/workspace/iedit/']
trust_level = "trusted"

[projects."/home/vsvetlov/workspace/keenable"]
trust_level = "trusted"

[projects."/home/vsvetlov/workspace/dots"]
trust_level = "trusted"

[projects."/home/seva"]
trust_level = "trusted"

[projects."/home/seva/workspace/keenable/keenable-model-trainer"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
